sudo: required

language: python

cache: pip

python:
  - "3.6"

stages:
  - clibrary
  - pybuild


branches:
  only:
    - py3
    - ctest

install:
  - sudo apt-get install libcmph0 libcmph-dev

jobs:
  include:
    - stage: clibrary
      script:
      - cmake .
      - make
      - ls -alh
      - ./test-create-and-query.o output.ddb src/tests/input.txt
      - ls -alh
    - stage: pybuild
      script:
      - cd python
      - python3 setup.py bdist_wheel --global-option="-I ../src/"
      - find . -name "*.so" | xargs -P1 -n1 ldd



