sudo: required

language: python

cache: pip

python:
  - "3.6"


branches:
  only:
    - py3
    - ctest

install:
  - sudo apt-get install libcmph0 libcmph-dev


script:
  - cmake .
  - make
  - ls -alh
  - ./test-create-and-query.o output.ddb src/tests/input.txt
  - ls -alh
  - install libdiscodb.so /usr/lib64/libdiscodb.so
  - install src/*.h /usr/include/.
  - cd python
  - python3 setup.py bdist_wheel
  - find . -name "*.so" | xargs -P1 -n1 ldd



